export const mockOrders = [
  {
    id: 1,
    user: "Juan Martinez",
    articles: [
      { id: 1007, description: "", weight: 3 },
      { id: 1008, description: "", weight: 5 },
    ],
    address: {
      Coordinates: "10,10",
      FirstName: "Juan",
      LastName: "Martinez",
      Street: "Calle Cedro",
      ZipCode: "74400",
      State: "Oaxaca",
      City: "Puerto Escondido",
      Neighbourhood: "Brizas de Zicatela",
      ExNumber: "73",
      InNumber: "1",
      PhoneNumber: "5512341234",
    },
    shippingId: 75,
    isCancelled: false,
    isRefunded: false,
  },
  {
    id: 2,
    user: "Juan Martinez",
    articles: [
      { id: 1001, description: "Product A", weight: 1 },
      { id: 1002, description: "Product B", weight: 2 },
      { id: 1003, description: "Product C", weight: 3 },
    ],
    address: {
      Coordinates: "10,10",
      FirstName: "Juan",
      LastName: "Martinez",
      Street: "Calle Cedro",
      ZipCode: "74400",
      State: "Oaxaca",
      City: "Puerto Escondido",
      Neighbourhood: "Brizas de Zicatela",
      ExNumber: "73",
      InNumber: "1",
      PhoneNumber: "5512341234",
    },
    shippingId: null,
    isCancelled: false,
    isRefunded: false,
  },
  {
    id: 3,
    user: "Juan Martinez",
    articles: [
      { id: 1004, description: "Product D", weight: 1.5 },
      { id: 1005, description: "Product E", weight: 2.5 },
      { id: 1006, description: "Product F", weight: 0.8 },
    ],
    address: {
      Coordinates: "10,10",
      FirstName: "Juan",
      LastName: "Martinez",
      Street: "Calle Cedro",
      ZipCode: "74400",
      State: "Oaxaca",
      City: "Puerto Escondido",
      Neighbourhood: "Brizas de Zicatela",
      ExNumber: "73",
      InNumber: "1",
      PhoneNumber: "5512341234",
    },
    shippingId: null,
    isCancelled: false,
    isRefunded: false,
  },
];
